[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "endstone-umoney"
version = "250310"
description = "null"

[project.entry-points."endstone"]
umoney = "endstone_umoney:umoney"